-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th6 10, 2020 lúc 05:32 AM
-- Phiên bản máy phục vụ: 10.1.40-MariaDB
-- Phiên bản PHP: 7.3.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `dantri`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `giaitri`
--

CREATE TABLE `giaitri` (
  `id` int(11) NOT NULL,
  `title` text COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci NOT NULL,
  `image` varchar(300) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `giaitri`
--

INSERT INTO `giaitri` (`id`, `title`, `description`, `image`) VALUES
(1, 'Hailey Bieber khoe eo thon khi cùng chồng đi cắm trại', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Cặp vợ chồng giàu có Hailey - Justin Bieber vui vẻ cùng nhau đi cắm trại tại một công viên ở Mỹ hôm 6/6 vừa qua.                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"Vợ Justin Bieber khoe dáng thon thả với áo tắm\" href=\"/giai-tri/vo-justin-bieber-khoe-dang-thon-tha-voi-ao-tam-20200417155941288.htm\">                                    <b> Vợ Justin Bieber khoe dáng thon thả với áo tắm</b>                              </a>                          </h3>                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"Justin Bieber đeo khẩu trang ra phố\" href=\"/giai-tri/justin-bieber-deo-khau-trang-ra-pho-20200314120934182.htm\">                                    <b> Justin Bieber đeo khẩu trang ra phố</b>                              </a>                          </h3>                  </div>', '6-1591495248762.jpg'),
(2, 'Người mẫu U50 trẻ trung trên sân tennis', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Dù đã ở tuổi 49 nhưng người mẫu Caprice Bourret vẫn sở hữu phom dáng trẻ trung, xinh đẹp đáng ngưỡng mộ.                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"&quot;Sao&quot; U50 Kate Beckinsale bốc lửa với áo tắm\" href=\"/giai-tri/sao-u-50-kate-beckinsale-boc-lua-voi-ao-tam-20191203100203381.htm\">                                    <b> \"Sao\" U50 Kate Beckinsale bốc lửa với áo tắm</b>                              </a>                          </h3>                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"Nữ MC U50 khoe cơ bụng trong ngày lễ giáng sinh\" href=\"/giai-tri/nu-mc-u-50-khoe-co-bung-trong-ngay-le-giang-sinh-20191225175314812.htm\">                                    <b> Nữ MC U50 khoe cơ bụng trong ngày lễ giáng sinh</b>                              </a>                          </h3>                  </div>', '3-1591491746660.jpg'),
(3, '&quot;Gái ế&quot; Song Ji Hyo bật mí dự định lập gia đình và ý định rời &quot;Running Man&quot;', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Trong bài phỏng vấn gần đây, Song Ji Hyo đã bật mí những dự định tương lai cùng ý nghĩa quan trọng của show truyền hình “Running Man” đối với chính cuộc sống và sự nghiệp của cô.                  </div>', 'ji-hyo-9-1591498150475.jpg'),
(4, 'Bảo Thy: “Tận hưởng cuộc sống hôn nhân rồi mới làm mẹ”', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Bảo Thy chia sẻ, cô và chồng sẽ dành một năm đầu để đi du lịch, tận hưởng cuộc sống, học hỏi kinh nghiệm để bản thân sẵn sàng bước vào hôn nhân, sau đó sẽ làm mẹ một cách một cách tốt nhất.                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"Bảo Thy lần đầu chia sẻ cuộc sống sau hôn nhân\" href=\"/giai-tri/bao-thy-lan-dau-chia-se-cuoc-song-sau-hon-nhan-20200118020749118.htm\">                                    <b> Bảo Thy lần đầu chia sẻ cuộc sống sau hôn nhân</b>                              </a>                          </h3>                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"Bảo Thy viết tâm thư sau đám cưới, khuyên các bạn gái “chậm mà chắc”\" href=\"/giai-tri/bao-thy-viet-tam-thu-sau-dam-cuoi-khuyen-cac-ban-gai-cham-ma-chac-20191118113547357.htm\">                                    <b> Bảo Thy viết tâm thư sau đám cưới, khuyên các bạn gái “chậm mà chắc”</b>                              </a>                          </h3>                  </div>', 'baothy-17-1591467734649.jpeg'),
(5, 'Rắc rối, thị phi đeo bám nhiều sao Việt tuần qua', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- MC Trấn Thành vướng phải tin đồn \"trên trời rơi xuống\" ảnh hưởng đến công việc; MC Kỳ Duyên thì đau đầu vì nhà hàng ở Mỹ bị người biểu tình đập phá, Lương Bằng Quang bị nhóm người lạ tấn công...                  </div>', 'tran-thanh-ky-duyen-1591461256178.jpg'),
(6, 'Ngưỡng mộ dáng săn chắc của vũ công Gabby Allen', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Người đẹp Gabby Allen sở hữu thân hình săn chắc, quyến rũ nhờ chăm chỉ tập gym và luyện vũ đạo mỗi ngày.                  </div>', '1-1591450539335.jpeg'),
(7, 'Kimberley Garner mặc áo tắm ra công viên', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Tranh thủ London ngày nắng đẹp, người mẫu Kimberley Garner diện áo tắm ra công viên vui chơi cùng bạn bè.                  </div>', '3-1591412488673.jpg'),
(8, 'Beaksang 2020: Son Ye Jin liếc mắt nhìn Hyun Bin khi lên nhận giải thưởng', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Giải thưởng nghệ sĩ được yêu thích nhất của giải Baeksang 2020, giải Oscar của điện ảnh Hàn Quốc, đã thuộc về cặp đôi của “Hạ cánh nơi anh” - Son Ye Jin và Hyun Bin.                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"Hyun Bin ôm Son Ye Jin tại tiệc ăn mừng “Hạ cánh nơi anh” kết thúc\" href=\"/giai-tri/hyun-bin-om-son-ye-jin-tai-tiec-an-mung-ha-canh-noi-anh-ket-thuc-20200217150958856.htm\">                                    <b> Hyun Bin ôm Son Ye Jin tại tiệc ăn mừng “Hạ cánh nơi anh” kết thúc</b>                              </a>                          </h3>                          <h3 class=\"h3relate\">                              <b>&gt;&gt;&nbsp;</b>                              <a title=\"Kim Hee Ae của “Thế giới hôn nhân” nói gì về nhân vật của mình?\" href=\"/giai-tri/kim-hee-ae-cua-the-gioi-hon-nhan-noi-gi-ve-nhan-vat-cua-minh-20200517115356812.htm\">                                    <b> Kim Hee Ae của “Thế giới hôn nhân” nói gì về nhân vật của mình?</b>                              </a>                          </h3>                  </div>', 'son-1-1591412661175.gif'),
(9, '40 tuổi, mỹ nhân xứ Đài - An Dĩ Hiên thông báo mang thai lần hai', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Ngôi sao điện ảnh nổi tiếng xứ Đài vừa thông báo với người hâm mộ rằng, cô đang mang thai đứa con thứ hai khi con trai đầu lòng chưa đầy 1 tuổi.                  </div>', 'hien-6-1591403425099.jpg'),
(10, '&quot;Sao&quot; tiếp tục biểu tình vì người da màu', '<div class=\"fon5 wid324 fl\">                      <span>(Dân trí)</span>&nbsp;- Nhiều ngôi sao nổi tiếng thế giới đã tham gia các cuộc biểu tình kêu gọi sự bình đẳng cho người da màu trên khắp nước Mỹ.                  </div>', '5-1591366636920.jpeg'),
(11, 'Hailey Bieber khoe eo thon khi c&ugrave;ng chồng đi cắm trại', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Cặp vợ chồng gi&agrave;u c&oacute; Hailey - Justin Bieber vui vẻ c&ugrave;ng nhau đi cắm trại tại một c&ocirc;ng vi&ecirc;n ở Mỹ h&ocirc;m 6/6 vừa qua.                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;Vợ Justin Bieber khoe d&aacute;ng thon thả với &aacute;o tắm&quot; href=&quot;/giai-tri/vo-justin-bieber-khoe-dang-thon-tha-voi-ao-tam-20200417155941288.htm&quot;&gt;                                    &lt;b&gt; Vợ Justin Bieber khoe d&aacute;ng thon thả với &aacute;o tắm&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;Justin Bieber đeo khẩu trang ra phố&quot; href=&quot;/giai-tri/justin-bieber-deo-khau-trang-ra-pho-20200314120934182.htm&quot;&gt;                                    &lt;b&gt; Justin Bieber đeo khẩu trang ra phố&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                  &lt;/div&gt;', '6-1591495248762.jpg'),
(12, 'Người mẫu U50 trẻ trung tr&ecirc;n s&acirc;n tennis', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- D&ugrave; đ&atilde; ở tuổi 49 nhưng người mẫu Caprice Bourret vẫn sở hữu phom d&aacute;ng trẻ trung, xinh đẹp đ&aacute;ng ngưỡng mộ.                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;&amp;quot;Sao&amp;quot; U50 Kate Beckinsale bốc lửa với &aacute;o tắm&quot; href=&quot;/giai-tri/sao-u-50-kate-beckinsale-boc-lua-voi-ao-tam-20191203100203381.htm&quot;&gt;                                    &lt;b&gt; &quot;Sao&quot; U50 Kate Beckinsale bốc lửa với &aacute;o tắm&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;Nữ MC U50 khoe cơ bụng trong ng&agrave;y lễ gi&aacute;ng sinh&quot; href=&quot;/giai-tri/nu-mc-u-50-khoe-co-bung-trong-ngay-le-giang-sinh-20191225175314812.htm&quot;&gt;                                    &lt;b&gt; Nữ MC U50 khoe cơ bụng trong ng&agrave;y lễ gi&aacute;ng sinh&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                  &lt;/div&gt;', '3-1591491746660.jpg'),
(13, '&amp;quot;G&aacute;i ế&amp;quot; Song Ji Hyo bật m&iacute; dự định lập gia đ&igrave;nh v&agrave; &yacute; định rời &amp;quot;Running Man&amp;quot;', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Trong b&agrave;i phỏng vấn gần đ&acirc;y, Song Ji Hyo đ&atilde; bật m&iacute; những dự định tương lai c&ugrave;ng &yacute; nghĩa quan trọng của show truyền h&igrave;nh &ldquo;Running Man&rdquo; đối với ch&iacute;nh cuộc sống v&agrave; sự nghiệp của c&ocirc;.                  &lt;/div&gt;', 'ji-hyo-9-1591498150475.jpg'),
(14, 'Bảo Thy: &ldquo;Tận hưởng cuộc sống h&ocirc;n nh&acirc;n rồi mới l&agrave;m mẹ&rdquo;', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Bảo Thy chia sẻ, c&ocirc; v&agrave; chồng sẽ d&agrave;nh một năm đầu để đi du lịch, tận hưởng cuộc sống, học hỏi kinh nghiệm để bản th&acirc;n sẵn s&agrave;ng bước v&agrave;o h&ocirc;n nh&acirc;n, sau đ&oacute; sẽ l&agrave;m mẹ một c&aacute;ch một c&aacute;ch tốt nhất.                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;Bảo Thy lần đầu chia sẻ cuộc sống sau h&ocirc;n nh&acirc;n&quot; href=&quot;/giai-tri/bao-thy-lan-dau-chia-se-cuoc-song-sau-hon-nhan-20200118020749118.htm&quot;&gt;                                    &lt;b&gt; Bảo Thy lần đầu chia sẻ cuộc sống sau h&ocirc;n nh&acirc;n&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;Bảo Thy viết t&acirc;m thư sau đ&aacute;m cưới, khuy&ecirc;n c&aacute;c bạn g&aacute;i &ldquo;chậm m&agrave; chắc&rdquo;&quot; href=&quot;/giai-tri/bao-thy-viet-tam-thu-sau-dam-cuoi-khuyen-cac-ban-gai-cham-ma-chac-20191118113547357.htm&quot;&gt;                                    &lt;b&gt; Bảo Thy viết t&acirc;m thư sau đ&aacute;m cưới, khuy&ecirc;n c&aacute;c bạn g&aacute;i &ldquo;chậm m&agrave; chắc&rdquo;&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                  &lt;/div&gt;', 'baothy-17-1591467734649.jpeg'),
(15, 'Rắc rối, thị phi đeo b&aacute;m nhiều sao Việt tuần qua', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- MC Trấn Th&agrave;nh vướng phải tin đồn &quot;tr&ecirc;n trời rơi xuống&quot; ảnh hưởng đến c&ocirc;ng việc; MC Kỳ Duy&ecirc;n th&igrave; đau đầu v&igrave; nh&agrave; h&agrave;ng ở Mỹ bị người biểu t&igrave;nh đập ph&aacute;, Lương Bằng Quang bị nh&oacute;m người lạ tấn c&ocirc;ng...                  &lt;/div&gt;', 'tran-thanh-ky-duyen-1591461256178.jpg'),
(16, 'Ngưỡng mộ d&aacute;ng săn chắc của vũ c&ocirc;ng Gabby Allen', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Người đẹp Gabby Allen sở hữu th&acirc;n h&igrave;nh săn chắc, quyến rũ nhờ chăm chỉ tập gym v&agrave; luyện vũ đạo mỗi ng&agrave;y.                  &lt;/div&gt;', '1-1591450539335.jpeg'),
(17, 'Kimberley Garner mặc &aacute;o tắm ra c&ocirc;ng vi&ecirc;n', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Tranh thủ London ng&agrave;y nắng đẹp, người mẫu Kimberley Garner diện &aacute;o tắm ra c&ocirc;ng vi&ecirc;n vui chơi c&ugrave;ng bạn b&egrave;.                  &lt;/div&gt;', '3-1591412488673.jpg'),
(18, 'Beaksang 2020: Son Ye Jin liếc mắt nh&igrave;n Hyun Bin khi l&ecirc;n nhận giải thưởng', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Giải thưởng nghệ sĩ được y&ecirc;u th&iacute;ch nhất của giải Baeksang 2020, giải Oscar của điện ảnh H&agrave;n Quốc, đ&atilde; thuộc về cặp đ&ocirc;i của &ldquo;Hạ c&aacute;nh nơi anh&rdquo; - Son Ye Jin v&agrave; Hyun Bin.                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;Hyun Bin &ocirc;m Son Ye Jin tại tiệc ăn mừng &ldquo;Hạ c&aacute;nh nơi anh&rdquo; kết th&uacute;c&quot; href=&quot;/giai-tri/hyun-bin-om-son-ye-jin-tai-tiec-an-mung-ha-canh-noi-anh-ket-thuc-20200217150958856.htm&quot;&gt;                                    &lt;b&gt; Hyun Bin &ocirc;m Son Ye Jin tại tiệc ăn mừng &ldquo;Hạ c&aacute;nh nơi anh&rdquo; kết th&uacute;c&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                          &lt;h3 class=&quot;h3relate&quot;&gt;                              &lt;b&gt;&amp;gt;&amp;gt;&amp;nbsp;&lt;/b&gt;                              &lt;a title=&quot;Kim Hee Ae của &ldquo;Thế giới h&ocirc;n nh&acirc;n&rdquo; n&oacute;i g&igrave; về nh&acirc;n vật của m&igrave;nh?&quot; href=&quot;/giai-tri/kim-hee-ae-cua-the-gioi-hon-nhan-noi-gi-ve-nhan-vat-cua-minh-20200517115356812.htm&quot;&gt;                                    &lt;b&gt; Kim Hee Ae của &ldquo;Thế giới h&ocirc;n nh&acirc;n&rdquo; n&oacute;i g&igrave; về nh&acirc;n vật của m&igrave;nh?&lt;/b&gt;                              &lt;/a&gt;                          &lt;/h3&gt;                  &lt;/div&gt;', 'son-1-1591412661175.gif'),
(19, '40 tuổi, mỹ nh&acirc;n xứ Đ&agrave;i - An Dĩ Hi&ecirc;n th&ocirc;ng b&aacute;o mang thai lần hai', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Ng&ocirc;i sao điện ảnh nổi tiếng xứ Đ&agrave;i vừa th&ocirc;ng b&aacute;o với người h&acirc;m mộ rằng, c&ocirc; đang mang thai đứa con thứ hai khi con trai đầu l&ograve;ng chưa đầy 1 tuổi.                  &lt;/div&gt;', 'hien-6-1591403425099.jpg'),
(20, '&amp;quot;Sao&amp;quot; tiếp tục biểu t&igrave;nh v&igrave; người da m&agrave;u', '&lt;div class=&quot;fon5 wid324 fl&quot;&gt;                      &lt;span&gt;(D&acirc;n tr&iacute;)&lt;/span&gt;&amp;nbsp;- Nhiều ng&ocirc;i sao nổi tiếng thế giới đ&atilde; tham gia c&aacute;c cuộc biểu t&igrave;nh k&ecirc;u gọi sự b&igrave;nh đẳng cho người da m&agrave;u tr&ecirc;n khắp nước Mỹ.                  &lt;/div&gt;', '5-1591366636920.jpeg');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `giaitri`
--
ALTER TABLE `giaitri`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `giaitri`
--
ALTER TABLE `giaitri`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
